version: "3"

services:
  rootnode:
    container_name: bootnode
    image: fuocnetwork/bootnode
    environment:
      - IP=127.0.0.1
      - PORT=30301
      - STATS_NAME=fuo-poa-bootnode
      - STATS_SECRET=secret
      - STATS_HOST=host
      - STATS_PORT=3000
    network_mode: "host"
    restart: always
    volumes:
      - ./node:/root/.ethereum
